projects:
  angularamplify:
    schemaPath: src/graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/graphql/graphql.service.ts
        docsFilePath: .
